### ISSUE TITLE
Сбои получения времени от серверов (wemos d1 mini)

### ISSUE THREAD

**Issue by aleta2020** [GyverLibs/GyverNTP#12]
Всем привет! Столкнулся с проблемой уже в 3х проекта (wemos d1 mini), использующих библиотеку GyverNTP (схема как в примере к библиотеке: инициируем, в лупе тикаем и при изменении секунд вывожу на лед-ленту время). Проблема: через разное время после включения питания МК (может через пару часов, а может через 2-3 суток - как повезет) возвращаемое объектом ntp время отстает от реального. Чаще всего ровно на 1 час (возможно связано с периодом обновления 3600 сек), но может и на 40 минут отставать и на  50. Сначала думал, что где-то в коде накосячил - переписывал код, дополнительно делал ручной апдейт, включал отладку и т.д. В сухом остатке сейчас: если появилось отставание, смотрю значения ntp.timeString();, ntp.status(); и ntp.synced(); - время показывает кривое, статус=0, synced=true; . В каком случае так может быть? Если даю команду updateNow(); - чаще возвращает корректное время с сервера, но может вернуть с разбегом в несколько минут или десятков. Если не давать команду updateNow();, то время само не восстанавливается ( период обновления задан GyverNTP ntp(3, 3600); ). После перезагрузки МК опять какое-то время все работает корректно. 
Заметил проблему, когда стал в коде для веб-морды использовать GyverPortal. С текущей версией GyverHub такая же ситуация. МК к WiFi подключен постоянно. Пробовал другие имена ntp-серверов - все аналогично.
Можно, конечно, тупо периодически перегружать МК или вместо updateNow инициировать командой begin. Но это же не совсем правильно...
Подскажите: где копать?

**Comment by GyverLibs** [comment]
Ох не знаю. Поставлю у себя тестировать на несколько дней попробую

**Comment by GyverLibs** [comment]
пока почти двое суток полёт нормальный
![image](https://github.com/GyverLibs/GyverNTP/assets/84599917/cda153d8-5a18-4f30-bac1-15cbbe1594b3)

**Comment by aleta2020** [comment]
Проблема в том, что отставание проявляется нестабильно. Часы включены постоянно и могут показывать правильное время и неделю и месяц. А потом в какой-то момент (вероятно есть какой-то фактор, влияющий на корректность данных) наступает период сбоев. Пока не вычислил этот фактор: может работа WiFi, может конфликт библиотек, может код где-то косячно написал, может китайские МК глючат, а может магнитные бури?  :-)  Была мысль, что NTP-сервера не те данные шлют (типа провайдер в этот период что-то переключает)... Буду искать дальше.

**Comment by GyverLibs** [comment]
Уф, изначально было 2-3 суток)) а тут оказывается месяц

**Comment by aleta2020** [comment]
месяц спрятался во фразу "как повезет"  ))   - точно не засекал: работает и работает. Как отстанет - начинаю ковырять... поставлю отладку и жду следующего раза... А крайний раз в течение суток раза 3-4 было отставание... В общем барабашка какой-то...

**Comment by GyverLibs** [comment]
Так, а если отключить асинхронный режим. Он вроде во всей обработкой ошибок работает, но стоит попробовать

**Comment by aleta2020** [comment]
Пробовал:
  _bool b = ntp.begin();
  ntp.asyncMode(false);   // выключить асинхронный режим
  ntp.ignorePing(true);   // не учитывать пинг до сервера_
  Первое, чем стал проверять - это async и ping - ничего не поменялось...
Если вручную не обновлять ntp, то ровно на 1 час отстает. 
Про минуты (когда отставание менее часа) думаю, что из-за того, что даю команду на ручное обновление в промежутке этого часа. А "сбой" происходит кратно 1 часу в момент синхронизации (т.к. время синхронизации 3600)...  Типа: МК в 12:10 стартанул, следующая синхронизация в 13:10 - она, например, "сбойная" - часы не обновляются (только минуты) - получаем после 13:09:59  - >  12:10:00 (вместо 13:10:00). А если сделать, например, в 12:50 ручную синхронизацию, то в 13:10 ntp вернет 12:50 - и отставание получается уже не 1 час, а 20 минут. 
Какая-то такая каша получается... Как-будто 2 значения времени в библиотеке по какой-то причине не синхронизируются должным образом... А "ловить" сложно, т.к. не знаешь, когда этот рассинхрон проявится...

**Comment by aleta2020** [comment]
Попробую задать время синхронизации не 1 час, а 45 минут - проверю гипотезу  :-)

**Comment by aleta2020** [comment]
Изменил период обновления на 45 минут. Все-равно через некоторое время произошло отставание ровно на 1 час. Более того, при подаче из приложения через консоль команды ручного обновления получилось следующее:
![image](https://github.com/GyverLibs/GyverNTP/assets/74668198/a2a26ae1-8432-4b2b-9840-e60b5173c1ec)
Когда заметил отставание, через консоль сначала (см. на скрине метку (1)) дал команду чтения времени ntp.timeString(), ntp.synced() и  ntp.status() - получил время, которое отставало от реального ровно на 1 час (6:10 вместо 7:10).
Потом даю команду ручного чтения ntp.updateNow() (см. 2) - получаю те же параметры, но корректно обновились только часы, а минуты сбросились в 0. Т.е. вместо 7:10 получаю 7:00.
Третий раз "старик забросил невод" - повторно даю команду ntp.updateNow() (см. 3) - получаю время 7:10 вместо 7:12 (к этому моменту время телефона уже такое - 2 минуты ушли на размышления :-) ).
Метка (4) - это то, что показывает дисплей часов. Метка (5) - это время телефона в момент получения сообщения (3).
Еще раз даю команду ручного обновления ntp (на скрине этого нету) - время становится корректным.
Во всех случаях ntp.synced() и  ntp.status(), которые вызываю сразу за updateNow, возвращают, что все ОК.
Вопросы (может и глупые, конечно, но хотелось бы докопаться до причин):
1. могут ли несколько МК, находящихся в одной сети при использовании этой библиотеки "мешать", друг другу?
2. можно ли в код библиотеки добавить контроль, чтобы другой код не "залезал" в адресное пространство (типа не портил данные, если таковое есть)? 
3. может я некорректно использую команды? - типа нельзя чаще какого-то времени повторно давать команду или нужно обязательно делать какую-то паузу...
Возможно, какие-то библиотеки друг другу "гадят". Попробую заменить GyverNTP на NTPClient - посмотрим методом исключения, что изменится...
Буду пробовать!!!
Кстати, ежедневная перезагрузка (у меня настроено в 00:00) не помогла. Т.е. "ошибка" не накапливается, а возникает произвольно. При этом сразу после перезагрузки время считывается корректно.

**Comment by GyverLibs** [comment]
1. В принципе да, это же UDP
2. Нет, в языке таких механизмов нет
3. Вроде бы ограничений нет, можно апдейтить хоть раз в секунду

Мой тестовый стенд всё ещё показывает корректное время)

**Comment by aleta2020** [comment]
1. как можно отловить эти "мешания"? и соответственно потом отфильтровать...

И еще вопрос: заменив библиотеку, можем получить вариант: "ошибка" исчезла - можно ли это считать, что проблема  в библиотеке?

**Comment by SoftFelix72** [comment]
У меня тоже самое проявление глюка. На ESP32. В рандомный промежуток времени время отстаёт ровно на час назад. Новая (очередная) синхронизация от NTP не меняет ситуацию, помогает только перезагрузка девайса. Такое впечатление, что где-то ломается TZ. Причём есть два абсолютно одинаковых девайса по железу и программе, но в одном установлен датчик BME680, а в другом BME280, с соответственно разными библиотеками. Оба девайса работают 24х7х365. Питание очень хорошее и стабильное. Так вот на девайсе с BME680 сбой времени (-1 час) происходит 1...3 раза в месяц, а на девайса с BME280 такое видел только один раз.

**Comment by GyverLibs** [comment]
на какой версии? Библиотека сильно обновилась и работает вообще по другому

**Comment by SoftFelix72** [comment]
> на какой версии? Библиотека сильно обновилась и работает вообще по другому

У меня ещё старая 1.3.1.  Новые версии 2.х без проблем заменяют версии 1.х ???

У меня там такая конструкция:

`if (ntp.synced()) {
        rtc.adjust(DateTime(ntp.year(), ntp.month(), ntp.day(), ntp.hour(), ntp.minute(), ntp.second()));
}`

И ещё вопрос: можно-ли получить дату-время от NTP-сервера уже из setup'а после установки соединения с роутером (WiFi.mode(WIFI_STA);)? Или NTP.tick(); в loop'е обязателен? Или достаточно только if (ntp.synced()) ???

**Comment by SoftFelix72** [comment]
Почти два месяца тому назад перекомпилировал проект на всех девайсах с библиотекой v2.1.2 (до этого была 1.3.1) и перепрошил. На данный момент аптайм почти 48 дней - всё работает отлично и сбоя времени на 1 час не было ни разу. Спасибо.

**Comment by GyverLibs** [comment]
Ураа
