### ISSUE TITLE
Часовой пояс должен быть в минутах

### ISSUE THREAD

**Issue by MalfurionST** [GyverLibs/GyverNTP#3]
Здравствуйте, библиотека очень интересная и если честно я давно жду что то подобное в Вашем исполнении, но корректировка часового пояса в часах не совсем корректна, т.к. в некоторых странах часовой пояс не ровно в часах а бывает и в 15 минут, очень хотелось бы увидеть это в следующей версии библиотеки...

**Comment by GyverLibs** [comment]
сделал `void setGMTminute(int16_t gmt)`. По умолчанию оставлю в часах, всё таки почти во всех странах он в часах
