### ISSUE TITLE
Уход времени

### ISSUE THREAD

**Issue by MalfurionST** [GyverLibs/GyverNTP#5]
Через некоторое время после запуска устройства, время сдвигается ровно на -1 час, в версии 1.2.1 такого не наблюдается...

**Comment by GyverLibs** [comment]
В синхронном или асинхронном режиме?

**Comment by MalfurionST** [comment]
Режим по умолчанию (асинхронный), через час время уже было -1 час от текущего

**Comment by MalfurionST** [comment]
Часто в Ваших библиотеках встречаю термин синхронный и асинхронный режим но до конца так и не понял в чем отличие... Хотя это наверное не здесь надо спрашивать но если не сложно ответьте пожалуйста...

**Comment by GyverLibs** [comment]
Синхронный - когда наступает обновление, программа ждёт ответа сервера внутри функции тик, в данном случае это может занимать до пары сотен миллисекунд. В асинхронном режиме всё работает гораздо более хитро и программа не ждёт ответа, тик не блокирует работу.

**Comment by MalfurionST** [comment]
Ок спасибо за разъяснение. Получается в асинхронном, вечером проверю в синхронном режиме по результату отпишусь...

**Comment by GyverLibs** [comment]
Я 12 часов назад запустил пример из библиотеки, время не ушло ни на секунду. Поэтому придется пройтись по пунктам:
- Версия библиотеки
- Какой используется МК
- Версия SDK (для ESP)
- Версия Arduino IDE
- Корректно ли работают ли встроенные примеры, в которых используются функции и конструкции, приводящие к багу в вашем коде
- Какой код загружался, какая работа от него ожидалась и как он работает в реальности
- В идеале приложить минимальный код, в котором наблюдается баг. Не полотно из тысячи строк, а минимальный код

**Comment by MalfurionST** [comment]
библиотека 1.3
ESP8266 ядро 2.7.4
Arduino IDE 1.8.19
в синхронном режиме работает нормально
примеры из библиотеки с применением своего кода завтра потестирую...

**Comment by GyverLibs** [comment]
Надо смотреть что в своём коде такого может быть, искать что ломает

**Comment by MalfurionST** [comment]
Проверил код, сбой происходит в асинхронном режиме в версии 1.3
вот логи:

до сбоя
20:51:56.496 -> dayAlPlot: 0
20:51:56.496 -> 29
20:51:56.496 -> 20:51
20:51:56.496 -> dayAl: 29
20:51:56.543 -> 1659095516 - timeClient.unix()

после
20:59:16.514 -> dayAlPlot: 0
20:59:16.514 -> 29
20:59:16.514 -> 19:59
20:59:16.514 -> dayAl: 29
20:59:16.514 -> 1659092356 - timeClient.unix()

**Comment by MalfurionST** [comment]
IDE v 1.8.19
esp8266 2.7.4

**Comment by GyverLibs** [comment]
Если пример из библиотеки работает корректно, значит "свой код" как то конфликтует с библиотекой. Что там? Может получится выделить минимальный код, при котором появляется баг?

**Comment by MalfurionST** [comment]
void getOpenWeather() {
  delay(1500);
  WiFiClient client;
  if (client.connect("api.openweathermap.org", 80)) {
    client.println("GET /data/2.5/weather?id=" + (String)cfg.city + "&appid=" + cfg.apik + "&units=metric HTTP/1.1");
    client.println("Host: api.openweathermap.org");
    client.println("Connection: close");
    client.println();
    bool flagR = 0;
    byte weatherIconTemp = 0;
    int16_t degreesTemp = 0;
    String lineR = "";
    String tempR = "";
    delay(1000);
    while (client.available()) {
      lineR = client.readStringUntil(',');
      if (lineR.indexOf("HTTP/1.1 200") != -1) { // если ответ 200 начать прием
        flagR = 1;
        weather.sourW = 1;
        Serial.print("sourW: ");
        Serial.println(weather.sourW);
      }

      //для отладки
      if (lineR.indexOf("HTTP/1.1") != -1) {
        Serial.println(lineR.substring(0, 12));
      }

      if (flagR && (lineR.indexOf("\"lon\":") != -1)) { // получаем долготу
        tempR = lineR.substring(lineR.indexOf("lon") + 5);
        weather.lon = tempR.toFloat();
        Serial.print("lon: ");
        Serial.println(weather.lon);
      }
      if (flagR && (lineR.indexOf("\"lat\":") != -1)) { // получаем широту
        tempR = lineR.substring(6, lineR.length() - 1);
        weather.lat = tempR.toFloat();
        Serial.print("lat: ");
        Serial.println(weather.lat);
      }
      if (flagR && (lineR.indexOf("\"icon\":") != -1)) { // получаем иконку погоды
        tempR = lineR.substring(8, lineR.length() - 4);
        weatherIconTemp = tempR.toInt();
        Serial.print("Icon: ");
        Serial.println(weatherIconTemp);
      }
      if (flagR && (lineR.indexOf("\"temp\":") != -1)) { // получаем реальную температуру
        tempR = lineR.substring(15);
        weather.tempR = round(tempR.toFloat());
        Serial.print("temp: ");
        Serial.println(weather.tempR);
      }
      if (flagR && (lineR.indexOf("\"feels_like\":") != -1)) { // получаем ощущаемую температуру
        tempR = lineR.substring(13);
        weather.tempF = round(tempR.toFloat());
        Serial.print("feels_like: ");
        Serial.println(weather.tempF);
      }
      if (flagR && (lineR.indexOf("\"pressure\":") != -1)) { // получаем давление
        tempR = lineR.substring(11);
        weather.presP = round(tempR.toFloat() / 1.333);
        Serial.print("pressure: ");
        Serial.println(weather.presP);
      }
      if (flagR && (lineR.indexOf("\"humidity\":") != -1)) { // получаем влажность
        tempR = lineR.substring(11);
        weather.humiP = tempR.toInt();
        Serial.print("humidity: ");
        Serial.println(weather.humiP);
      }
      if (flagR && (lineR.indexOf("\"speed\":") != -1)) { // получаем скорость ветра
        tempR = lineR.substring(16);
        weather.windS = round(tempR.toFloat());
        Serial.print("speed: ");
        Serial.println(weather.windS);
      }
      if (flagR && (lineR.indexOf("\"deg\":") != -1)) { // получаем направление ветра
        tempR = lineR.substring(6);
        degreesTemp = tempR.toInt();
        Serial.print("deg: ");
        Serial.println(degreesTemp);
      }
      if (flagR && (lineR.indexOf("\"gust\":") != -1)) { // получаем скорость ветра
        tempR = lineR.substring(7, lineR.length() - 1);
        weather.windG = round(tempR.toFloat());
        Serial.print("speed 2: ");
        Serial.println(weather.windG);
      }
      if (flagR && (lineR.indexOf("\"timezone\":") != -1)) { // получаем часовой пояс
        tempR = lineR.substring(11);
        weather.zoneT = (tempR.toInt()) / 60;
        Serial.print("timezone: ");
        Serial.println(weather.zoneT);
      }
      if (flagR && (lineR.indexOf("\"name\":") != -1)) { // получаем имя города
        tempR = lineR.substring(8, lineR.length() - 1);
        tempR.toCharArray(weather.cityN, tempR.length() + 1);
        Serial.print("name: ");
        Serial.println((String)weather.cityN);
      }
      delay(100);
    }
    if (flagR) { // если получили данные переводим направление ветра, иконку погоды и устанавливаем часовой пояс
      weather.windD = windDirection(degreesTemp);
      weather.iconW = weatherIcons(weatherIconTemp);
      if (cfg.zoneT != weather.zoneT) {
        timeClient.setGMTminute(weather.zoneT);
        cfg.zoneT = weather.zoneT;
        memory.update();
        Serial.print("изменение часового пояса");
      }
      weatherCount = 0;
    } else {
      if (weatherCount < 3) {
        ++weatherCount;
        weatherTimer.force();
      } else {
        weatherCount = 0;
      }
    }
    Serial.println();
    Serial.println("closing connection");
  } else {
    weatherTimer.force();
  }
}

**Comment by MalfurionST** [comment]
между только по таймеру сработал этот код...

**Comment by GyverLibs** [comment]
ох и полотно. Ну здесь всё просто: вот в этой строке
```cpp
timeClient.setGMTminute(weather.zoneT);
```
Меняется часовой пояс, поэтому время убегает ровно на час. Асинхронность и вообще работа GyverNTP здесь непричём

**Comment by MalfurionST** [comment]
выше условие 
if (cfg.zoneT != weather.zoneT)
если скачаный часовой пояс не равен сохраненному в памяти то изменить часовой пояс
я специально вывел в сериал сообщение в случае сработки условия, оно не срабатывало
часовой пояс и до и после был +540 минут (9 часов)
тем более в синхронном режиме такой проблемы нет

**Comment by MalfurionST** [comment]
10:01:48.640 -> dayAlPlot: 0
10:01:48.640 -> 30
10:01:48.640 -> 10:1
10:01:48.640 -> dayAl: 30
10:01:48.687 -> 1659142908
10:01:48.687 -> 540
10:01:48.687 -> 540
10:01:48.687 -> 
10:01:53.903 -> sourW: 1
10:01:53.903 -> HTTP/1.1 200
10:01:54.092 -> lon: 129.41
10:01:54.188 -> lat: 49.78
10:01:54.568 -> Icon: 4
10:01:54.804 -> temp: 25
10:01:54.900 -> feels_like: 26
10:01:55.184 -> pressure: 757
10:01:55.278 -> humidity: 76
10:01:55.704 -> speed: 3
10:01:55.800 -> deg: 272
10:01:55.895 -> speed 2: 3
10:01:56.508 -> timezone: 540
10:01:56.698 -> name: Raychikhinsk
10:02:01.942 -> 
10:02:01.942 -> closing connection
10:11:48.645 -> 
10:11:48.645 -> dayAlPlot: 0
10:11:48.645 -> 30
10:11:48.645 -> 9:11
10:11:48.645 -> dayAl: 30
10:11:48.692 -> 1659139908
10:11:48.692 -> 540
10:11:48.692 -> 540
вотлоги

**Comment by GyverLibs** [comment]
Значит жду минимальный код, при котором наблюдается баг. И не куском, а полностью, со всеми инклудами. Возможно кто то перехватывает udp соединение, пока библиотека ждёт ответ в асинхронном режиме, и в итоге получается мусор

**Comment by MalfurionST** [comment]
https://disk.yandex.ru/d/cnIODwycBTvUqw
полный код тут, разрабатываю как модуль для вашей метеостанции

**Comment by MalfurionST** [comment]
и фастбот версии 1.19 тоже уже оставил комментарий начиная с версии 1.20 не компилируется

**Comment by GyverLibs** [comment]
> начиная с версии 1.20 не компилируется

скорее всего пофикшено в 1.22

**Comment by MalfurionST** [comment]
спс не видел что уже новая версия вышла.
сейчас начал оптимизировать портал и под него переписывать код.

**Comment by GyverLibs** [comment]
то есть 1.2.1 работает стабильно долгое время, а 1.3 в любом случае ломается? Я вообще не понимаю как такое возможно, 1.3 отличается от 1.2.1 значением переменной таймера, по которому вызывается обновление, то есть внутренний "тик" просто отрабатывает первый запуск чуть быстрее
https://github.com/GyverLibs/GyverNTP/commit/0ff7cda9a91b2dd7fb282e21b6a00ab5bb72c6ee#diff-b3ffeb7f6db94f78b39a848e123183b045b72ac6d145ff22e76abb570fb94e46

**Comment by MalfurionST** [comment]
да в версии 1.2.1 проверял в течении недели с настройками "по умолчанию" (асинхронный режим) на версии 1.3 в асинхронном примерно через час (может 50 минут) уходит на ровно -1 час. При этом в синхронном режиме работает стабильно (проверял в течении суток).  При этом первый запрос погоды после включения проходит стабильно, а после второго получаю -1 час. Еще была ситуация что после нажатия кнопки "ок" на странице "настройки портала" время вроде выровнялось, но больше на такую ситуацию я не попал...

**Comment by MalfurionST** [comment]
завтра попробую перед вызовом функции вывести время и после нее, по результату отпишусь...

**Comment by GyverLibs** [comment]
значит запрос погоды как то ломает связь с ntp сервером. Нужно локализовать проблему и напихать отладки вовнутрь GyverNTP

**Comment by GyverLibs** [comment]
в версии 1.2.1 возможно этого не происходит, потому что фаза запроса к NTP серверу "сдвигается" по времени относительно запуска программы

**Comment by MalfurionST** [comment]
Вообще понимаю что не по теме но давно хотел сказать Вам СПАСИБО! за ваши уроки и сайт. Когда я учился в РГРТА и изучал "турбо паскаль"  и BAT с DOS вообще не видел практического для себя применения всего этого. Теперь конечно уже поздно (РГРТА я не закончил) но это стало моим основным хобби.

**Comment by GyverLibs** [comment]
всегда пожалуйста) у bat и dos практических применений не так много, в отличие от микроконтроллеров. Их можно хотя бы пощупать)

**Comment by MalfurionST** [comment]
это конечно но первый скрипт, который уже работает больше 7 лет, по резервному копированию баз 1С я все-же написал на BAT ;-)

**Comment by GyverLibs** [comment]
Можно кстати попробовать такой вариант: исключить запрос погоды в момент ожидания ответа от NTP сервера:
```cpp
if (!ntp.busy()) {
  // выполнять запросы и прочие тяжёлые конструкции
}
```
