### ISSUE TITLE
Ошибка при обновлении времени

### ISSUE THREAD

**Issue by true-nomad** [GyverLibs/GyverNTP#6]
Здравствуйте.
У меня возникает ошибка при обновлении времени с сервера.
Возникновение ошибки почему-то зависит от режима подключения по WiFi.
Вот минимальный код для воспроизведения:
//================== main.cpp ===============
#include <Arduino.h>
#include <GyverNTP.h>

#define WIFI_PHY_MODE WIFI_PHY_MODE_11B
//#define WIFI_PHY_MODE WIFI_PHY_MODE_11G
//#define WIFI_PHY_MODE WIFI_PHY_MODE_11N

#define STASSID "test"
#define STAPSK  "11111111"

GyverNTP ntp(3);

void setup() {
  Serial.begin(115200);
  //Serial.setDebugOutput(true);

  Serial.println("==  Connecting to WiFi ...");
  if(WiFi.getPhyMode() != WIFI_PHY_MODE){
      WiFi.setPhyMode(WIFI_PHY_MODE);
  }
  WiFi.mode(WIFI_STA);
  WiFi.begin(STASSID, STAPSK);
  wl_status_t wifistatus;
  do{
    wifistatus = (wl_status_t)WiFi.waitForConnectResult(750);
  } while(wifistatus != WL_CONNECTED);

  Serial.println("==  WiFi connected");
  ntp.begin();
}

time_t t1;

void loop() {
  if(millis()-t1 > 10000) {
      Serial.println("==  updating time...");
      uint8_t status = ntp.updateNow();
      t1=millis();
      Serial.printf("==  status: %d, time:%s\r\n", status, ntp.timeString());
  }else{
      delay(30);
  }
}
//=========================================

При выполнении этого кода, в зависимости от физического типа подключения по wi-fi, спустя определенное число запросов
перестает приходить ответ от сервера (статус 3).
При подключении по стандарту 11b это происходит после 2 запросов. При подключении по стандарту 11g - через 12 запросов. При подключении по стандарту 11n - точно не подсчитывал - но через какое-то время тоже возникает ошибка.
 Справедливости ради должен сказать что до Вашей библиотеки использовал другую, и там тоже возникала ошибка через такое-же количество запросов.
Пробовал менять сам модуль esp8266, чтобы исключить аппаратную проблему (использую китайские модули esp12f) - не помогло.

**Comment by GyverLibs** [comment]
Значит проблема в самом режиме либо во встроенных стандартных библиотеках. Здесь просто отправляется UDP запрос и принимается ответ

**Comment by true-nomad** [comment]
Спасибо за ответ. 
Хотелось бы, если это возможно, подтвердить или опровергнуть наличие проблемы у других пользователей или у Вас.
Уже довольно долго ищу причину и не могу найти. Одно дело если проблема только у меня и совсем другое если она повторяется у других.

**Comment by GyverLibs** [comment]
То есть связь с сервером пропадает независимо от режима работы wifi, потому что их всего три и на всех наблюдается проблема?

**Comment by GyverLibs** [comment]
У меня на всех режимах работает стабильно, проверил по 30 запросов каждые 10 секунд как в коде выше

**Comment by true-nomad** [comment]
> То есть связь с сервером пропадает независимо от режима работы wifi, потому что их всего три и на всех наблюдается проблема?

Да. На всех трех. Спасибо что проверили - буди искать дальше.
Проблему заметил давно. Примерно год назад. Тогда и начал копать. Но, перешел на подключение по стандарту 11n, где проблема возникает через значительно большее количество запросов. Да и в реальном коде синхронизация времени происходит значительно реже, поэтому благополучно забыл о проблеме.
 Но за год использования устройства выяснилось что в режиме 11n подключение работает не стабильно, в отличии от 11g и 11b. Вернулся к этим режимам и вспомнил о проблеме синхронизации времени, так как она снова стала актуальной.
Я предполагаю, что в силу своего малого опыта по работе с esp8266 я не учитываю какие-то внешние, относительно библиотеки ntp, факторы.
Например совсем недавно выяснил, что режим работы по wifi запоминается и не меняется даже после перепрошивки, если его явно не изменить в коде. По этой причине долго не мог понять почему в разных модулях проблема с udp запросом в библиотеке происходит через различное (но не меняющееся при перезагрузке) количество запросов.
Возможно есть еще неведомые мне режимы esp, которые нужно явно установить в коде, чтобы мои модули не отличались от тех, в которых проблем с  синхронизацией не возникают.

**Comment by GyverLibs** [comment]
Либо что то с роутером, либо брак есп
