### ISSUE TITLE
Проблема с месяцем

### ISSUE THREAD

**Issue by samoswall** [GyverLibs/GyverNTP#7]
Собственно код:

     valDate=ntp.dateString();
     valTime=ntp.timeString();
     portal.updateDate("date", valDate);
     portal.updateTime("time", valTime);

Все отлично, только месяц **00**
![image](https://user-images.githubusercontent.com/80251553/201548914-e14e10eb-9ecf-470e-a7de-a3da936d816c.png)

**Comment by GyverLibs** [comment]
странно
![image](https://user-images.githubusercontent.com/84599917/201550362-a00c25c4-cda5-405d-953d-171a54263d80.png)

```cpp
void build() {
  GP.BUILD_BEGIN();
  GP.THEME(GP_DARK);
  
  GP.UPDATE("tm,dt");

  GP.LABEL("date", "tm");
  GP.LABEL("time", "dt");

  GP.BUILD_END();
}

void action() {
  if (portal.update()) {
    String t = ntp.timeString();
    String d = ntp.dateString();
    portal.updateString("tm", t);
    portal.updateString("dt", d);
  }
}
```

Но так выводить некрасиво, строки создаются при каждом обновлении. Лучше так
```cpp
  if (portal.update()) {
    if (portal.update("tm"))  portal.answer(ntp.timeString());
    if (portal.update("dt"))  portal.answer(ntp.dateString());
  }
```
