### ISSUE TITLE
GyverNTP 

### ISSUE THREAD

**Issue by Security000** [GyverLibs/GyverNTP#8]
В файле GyverNTP.h есть функция :
// миллисекунд с последнего обновления (с 0 секунд unix)
    uint32_t msFromUpdate() {return millis() - _last_upd;}

В файле keywords.txt отсутствует упоминание этой функции:
msFromUpdate	KEYWORD2

**Comment by GyverLibs** [comment]
Это вроде внутренняя функция для нужд библиотеки
